import pytz
import datetime
year=int(input())
month=int(input())
day=int(input())
hour=int(input())
minutes=int(input())
user_time=datetime.datetime(year,month,day,hour,minutes)
cairo_zone=pytz.timezone('Africa/Cairo')
london_zone=pytz.timezone('UTC')
delhi_zone=pytz.timezone('Asia/Kolkata')
sydney_zone=pytz.timezone('Australia/Sydney')
tokyo_zone=pytz.timezone('Asia/Tokyo')
seoul_zone=pytz.timezone('Asia/Seoul')
cairo_time=pytz.utc.localize(user_time).astimezone(cairo_zone)
london_time=pytz.utc.localize(user_time).astimezone(london_zone)
delhi_time=pytz.utc.localize(user_time).astimezone(delhi_zone)
sydney_time=pytz.utc.localize(user_time).astimezone(sydney_zone)
tokyo_time=pytz.utc.localize(user_time).astimezone(tokyo_zone)
seoul_time=pytz.utc.localize(user_time).astimezone(seoul_zone)

print('Cairo Time is',cairo_time.isoformat())
print('London Time is',london_time.isoformat())
print('New Delhi Time is',delhi_time.isoformat())
print('Sydney Time is',sydney_time.isoformat())
print('Tokyo Time is',tokyo_time.isoformat())
print('Seoul Time is',seoul_time.isoformat())